In [17]:
import pandas as pd
import numpy as np
df = pd.DataFrame({
    'Age': [25, 30, np.nan, 40, 35],
    'Department': ['HR', 'Finance', 'Finance', np.nan, 'IT']
})
df['Age'].fillna(df['Age'].mean(), inplace=True)
df['Department'].fillna(df['Department'].mode()[0], inplace=True)
df

Original Data:

After Mean/Mode Imputation:

/tmp/ipykernel_7244/2846059820.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(), inplace=True)
/tmp/ipykernel_7244/2846059820.py:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Department'].fillna(df['Department'].mode()[0], inplace=True)

    Age Department
0  25.0         HR
1  30.0    Finance
2  32.5    Finance
3  40.0    Finance
4  35.0         IT

In [18]:
df = pd.DataFrame({
    'Age': [25, 30, np.nan, 40, 35]
})
df['Age'].fillna(df['Age'].median(), inplace=True)
df

/tmp/ipykernel_7244/1010078913.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].median(), inplace=True)

    Age
0  25.0
1  30.0
2  32.5
3  40.0
4  35.0

In [19]:
df = pd.DataFrame({
    'Sales': [100, np.nan, np.nan, 250, 300]
})
df_ffill = df.copy()
df_ffill.fillna(method='ffill', inplace=True)
df_ffill

/tmp/ipykernel_7244/2551996929.py:5: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_ffill.fillna(method='ffill', inplace=True)

   Sales
0  100.0
1  100.0
2  100.0
3  250.0
4  300.0

In [20]:
df = pd.DataFrame({
    'Sales': [100, np.nan, np.nan, 250, 300]
})
df_bfill = df.copy()
df_bfill.fillna(method='bfill', inplace=True)
df_bfill

/tmp/ipykernel_7244/3878350235.py:5: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_bfill.fillna(method='bfill', inplace=True)

   Sales
0  100.0
1  250.0
2  250.0
3  250.0
4  300.0

In [22]:
df = pd.DataFrame({
    'Age': [25, 30, np.nan, 40, 35],
    'Department': ['HR', 'Finance', 'Finance', np.nan, 'IT']
})
df_drop_rows = df.dropna()
df_drop_rows

    Age Department
0  25.0         HR
1  30.0    Finance
4  35.0         IT

In [23]:
df = pd.DataFrame({
    'Age': [25, 30, np.nan, 40, 35],
    'Department': ['HR', 'Finance', 'Finance', np.nan, 'IT']
})
df_drop_cols = df.dropna(axis=1)
df_drop_cols

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [24]:
df = pd.DataFrame({
    'Age': [25, 30, np.nan, 40, 35],
    'Salary': [50000, np.nan, 60000, 70000, np.nan],
    'Department': ['HR', 'Finance', 'Finance', np.nan, 'IT']
})
df
df_mean = df.copy()
df_mean['Age'].fillna(df_mean['Age'].mean(), inplace=True)
df_median = df.copy()
df_median['Salary'].fillna(df_median['Salary'].median(), inplace=True)
df_mode = df.copy()
df_mode['Department'].fillna(df_mode['Department'].mode()[0], inplace=True)
df_ffill = df.copy()
df_ffill.fillna(method='ffill', inplace=True)
df_bfill = df.copy()
df_bfill.fillna(method='bfill', inplace=True)
df_drop_rows = df.dropna()
df_drop_cols = df.dropna(axis=1)
df_mean
df_median
df_mode
df_ffill
df_bfill
df_drop_rows
df_drop_cols

/tmp/ipykernel_7244/3992092296.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_mean['Age'].fillna(df_mean['Age'].mean(), inplace=True)
/tmp/ipykernel_7244/3992092296.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_median['Salary'].fillna(df_median['Salary'].median(), inplace=True)
/tmp/ipykernel_7244/3992092296.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_mode['Department'].fillna(df_mode['Department'].mode()[0], inplace=True)
/tmp/ipykernel_7244/3992092296.py:14: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_ffill.fillna(method='ffill', inplace=True)
/tmp/ipykernel_7244/3992092296.py:16: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_bfill.fillna(method='bfill', inplace=True)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]